### PR TITLE
feat(mobile): [Transaction] add basic transaction amount input

### PR DESCRIPTION
**Pull request by bkdev98**
https://github.com/sixpm-ai/6pm/assets/16166195/da1d82b7-ef35-49ae-90e0-640a29dcd656

### CODE REVIEW

**Comment by bkdev98** [comment]
* **#93** <a href="https://app.graphite.dev/github/pr/sixpm-ai/6pm/93?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bkdev98 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by duongdev** [comment]
The `VND` is overflow during animation

CleanShot 2024-07-09 at 18 25 31@2x

**Comment by bkdev98** [comment]
> The `VND` and numbers are overflow during animation
> 
> CleanShot 2024-07-09 at 18 25 31@2x

Fixed 🔧

https://github.com/sixpm-ai/6pm/assets/16166195/40c754e7-0922-43e5-8717-4498a1d73114

**Review by duongdev — APPROVED** [review]

**Comment by duongdev** [comment]
### Merge activity

* **Jul 10, 11:51 PM EDT**: @duongdev started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/sixpm-ai/6pm/93).

**Pull request merged**
